experiment:
  context:
    name: TDNQ-lgap
    devices: [0,1,2,3]
    multi-p: False
    dist: False

  main_loop:
    warmup: 
      student_nums: 20
      supervisor_iters: 5
    nums: 200
    student_nums: 5

  student:
    dataloader:
      name: cifar10 # default cifar10
      batch_size: 512
      epochs: 100
      da: False
    model:
      name: dnn # default dnn
      units: [128,64,32,10] # default 128,64,64,32
      activations: [relu,relu,relu,softmax] # default relu
    loss:
      name: CategoricalCrossentropy
    metrics: 
      name: categorical_accuracy
    optimizer:
      name: sgd # default SGD
      learning_rate: 0.1 # default 0.01
    train_loop:
        train:
          lr_decay: False
          action: fix_n
          policy: e_greedy
        valid:
          q_mode: TD-NQ
          weight_space: sum_reduce
          valid_gap: 10

  supervisor:
    dataloader:
      name: dnn_sr_RL
      exp: decay
      replay_window: 32
      batch_size: 32
      epochs: 10
    model:
      name: dnn # default dnn
      units: [128,64,32,5] # default 128,64,64,32
      embedding: True
      activations: [relu,relu,relu,relu] # default relu
    optimizer:
      name: sgd
      learning_rate: 0.01
    loss:
      name: MeanSquaredError #MeanAbsoluteError 
    train_loop:
        valid:
          valid_gap: 10000 