experiment:
  context:
    name: cifar10-MATD-NL #for each exp
    # devices: 1
    # multi-p: 1
    # dist:
    #   devices: 4
    log_path: ./log

  main_loop:
    warmup: 
      student_nums: 10
      supervisor_iters: 1
    nums: 100
    student_nums: 3

  student:
    name: naive
    dataloader:
      name: cifar10 # cifar100, mnist
      batch_size: 512
      epochs: 120
      da: False # data augumentation
    model:
      name: dnn 
      units: [128,64,32,10] 
      activations: [relu,relu,relu,softmax] 
    loss:
      name: CategoricalCrossentropy
    metrics: 
      name: CategoricalAccuracy
    optimizer:
      name: sgd 
      learning_rate: 0.1 
    train_loop:
        train:
          lr_decay: False # decay
          discount_factor: 0.9
          action:
            style: fix_n
            act_space: [0.1,0.5,1.0,2.5,5.0]
          policy: 
            style: epsilon_greedy
            epsilon: 0.50
        valid:
          q_style: multi_action_temporal_diffrernce #multi_action
          save_knowledge: ["state", "reward", "act_idx"]
          discount_factor: 0.9
          weights_style: flat_imagelization # imagelization
          valid_gap: 30
          online: False
        test:
          epoch: -1
        visual: False

  supervisor:
    name: naive
    dataloader:
      name: dnn_RL
      exp: decay
      replay_window: 10
      batch_size: 32
      epochs: 30
    model:
      name: dnn # default dnn
      units: [128,64,32,5] # default 128,64,32,5
      activations: [relu,relu,relu,relu] # default relu
      normalization: True
      downsampling: True
    optimizer:
      name: sgd
      learning_rate: 0.1
    loss:
      name: MeanSquaredError #MeanAbsoluteError 
    metrics: 
      name: MeanSquaredError
    train_loop:
        train:
          lr_decay: False # decay
          weights_style: flat_imagelization # stack_imagelization
        valid:
          valid_gap: 100
          epoch: -1
        test:
          epoch: -1