experiment:
  context:
    name: tki

  main_loop:
    warmup: 
      student_nums: 0
      supervisor_trains: 1
    nums: 10
    student_nums: 0

  student:
    dataloader:
      name: cifar10 # default cifar10
      epochs: 10
    model:
      name: dnn # default dnn
    loss:
      name: SparseCategoricalCrossentropy
    metrics: 
      name: SparseCategoricalAccuracy,Mean
    optimizer:
      name: Adam # default SGD
      learning_rate: 0.001 # default 0.01
    train_loop:
        valid:
          valid_gap: 100 

  supervisor:
    dataloader:
      name: dnn_weights
      batch_size: 16
      epochs: 10
    model:
      name: dnn # default dnn
    optimizer:
      name: SGD
      learning_rate: 0.001
    loss:
      name: mean_squared_error
    train_loop:
        valid:
          valid_gap: 100 