experiment:
  context:
    name: cifar10-da #for each exp
    devices: 4
    multi-p: False
    dist: False
    log_path: ./log

  main_loop:
    warmup: 
      student_nums: 10
      supervisor_trains: 1
    nums: 100
    student_nums: 1

  student:
    name: gpu4-ep100
    dataloader:
      name: cifar10 # cifar100, mnist
      batch_size: 512
      epochs: 100
      da: True # data augumentation
    model:
      name: dnn 
      units: [128,64,32,10] 
      activations: [relu,relu,relu,softmax] 
    loss:
      name: CategoricalCrossentropy
    metrics: 
      name: categorical_accuracy
    optimizer:
      name: sgd 
      learning_rate: 0.1 
    train_loop:
        train:
          lr_decay: False # decay
          action: fix
          policy: e_greedy
        valid:
          q_mode: TD
          weight_space: norm_reduce
          valid_gap: 10
        test:
          epoch: -1

  supervisor:
    dataloader:
      name: dnn_sr_RL
      exp: decay
      replay_window: 25
      batch_size: 128
      epochs: 10
    model:
      name: dnn # default dnn
      units: [128,64,32,1] # default 128,64,64,32
      embedding: True
      activations: [relu,relu,relu,relu] # default relu
    optimizer:
      name: sgd
      learning_rate: 0.01
    loss:
      name: MeanSquaredError #MeanAbsoluteError 
    train_loop:
        valid:
          valid_gap: 10000 